# general configuration
version: '{branch}.{build}'

# environment configuration
image: Visual Studio 2017
clone_folder: c:\projects\zstd
environment:
  BIN_SDK_VER: 2.2.0
  DEP: libzstd-1.4.5
  matrix:
    - PHP_VER: 7.2
      ARCH: x64
      TS: 0
      VC: vc15
    - PHP_VER: 7.2
      ARCH: x86
      TS: 1
      VC: vc15
    - PHP_VER: 7.3
      ARCH: x64
      TS: 0
      VC: vc15
    - PHP_VER: 7.3
      ARCH: x86
      TS: 1
      VC: vc15
    - PHP_VER: 7.4
      ARCH: x64
      TS: 0
      VC: vc15
    - PHP_VER: 7.4
      ARCH: x86
      TS: 1
      VC: vc15
cache:
  - c:\build-cache -> .appveyor.yml, .appveyor\install.ps1
install:
  - ps: .appveyor\install.ps1

# build configuration
build_script:
  - ps: .appveyor\build.ps1

# tests configuration
test_script:
  - ps: .appveyor\test.ps1
